#### Importing libries to the project

In [249]:
import pandas as pd
import numpy as np
import psycopg2
import os
from io import StringIO

#### Importing Datasets

In [250]:
dfIdadeGenero = pd.read_json('Datasets\Tabela_idade_e_genero.json')

In [251]:
dfIdadeGenero

,Idade,Gênero,Dia,FIELD4,Alcance,Impressões,Quantia gasta (BRL),Cliques no link,Visualizações por página,Compras no website,Compras no facebook,Adicionados ao carrinho,Valor de conversão adicionado ao carrinho,Checkouts Iniciados,Valor de conversão de checkouts iniciados,Valor de conversão de compras,Compras
0,45-54,Feminino,2021-07-31,,1116.0,1489.0,"9,42","24,00","20,00",,,"1,00","63,90","1,00",,,
1,35-44,Outros,2021-07-31,,4.0,5.0,"0,03",,,,,,,,,,
2,45-54,Outros,2021-07-31,,3.0,3.0,,,,,,,,,,,
3,65+,Masculino,2021-07-31,,24.0,36.0,"0,11",,,,,,,,,,
4,25,Outros,2021-07-31,,4.0,4.0,"0,01",,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
506,55-64,Masculino,2021-07-01,,400.0,400.0,"1,07","2,00","1,00",,,,,,,,
507,65+,Feminino,2021-07-01,,212.0,230.0,"0,88","2,00","1,00",,,,,,,,
508,65+,Masculino,2021-07-01,,136.0,157.0,"0,48",,,,,,,,,,
509,25-34,Outros,2021-07-01,,4.0,4.0,,,,,,,,,,,
510,35-44,Outros,2021-07-01,,NaN,5.0,"0,03",,,,,,,,,,

Replacing (,) to (.)

In [252]:
dfIdadeGenero = dfIdadeGenero.replace({',': '.'}, regex=True)

In [253]:
dfIdadeGenero

,Idade,Gênero,Dia,FIELD4,Alcance,Impressões,Quantia gasta (BRL),Cliques no link,Visualizações por página,Compras no website,Compras no facebook,Adicionados ao carrinho,Valor de conversão adicionado ao carrinho,Checkouts Iniciados,Valor de conversão de checkouts iniciados,Valor de conversão de compras,Compras
0,45-54,Feminino,2021-07-31,,1116.0,1489.0,9.42,24.00,20.00,,,1.00,63.90,1.00,,,
1,35-44,Outros,2021-07-31,,4.0,5.0,0.03,,,,,,,,,,
2,45-54,Outros,2021-07-31,,3.0,3.0,,,,,,,,,,,
3,65+,Masculino,2021-07-31,,24.0,36.0,0.11,,,,,,,,,,
4,25,Outros,2021-07-31,,4.0,4.0,0.01,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
506,55-64,Masculino,2021-07-01,,400.0,400.0,1.07,2.00,1.00,,,,,,,,
507,65+,Feminino,2021-07-01,,212.0,230.0,0.88,2.00,1.00,,,,,,,,
508,65+,Masculino,2021-07-01,,136.0,157.0,0.48,,,,,,,,,,
509,25-34,Outros,2021-07-01,,4.0,4.0,,,,,,,,,,,
510,35-44,Outros,2021-07-01,,NaN,5.0,0.03,,,,,,,,,,

#### Replacing nothing to 0 (this is necessary due to the conversion of columns type to int)

In [254]:
dfIdadeGenero = dfIdadeGenero.replace({'': '0'}, regex=True)

In [255]:
dfIdadeGenero

,Idade,Gênero,Dia,FIELD4,Alcance,Impressões,Quantia gasta (BRL),Cliques no link,Visualizações por página,Compras no website,Compras no facebook,Adicionados ao carrinho,Valor de conversão adicionado ao carrinho,Checkouts Iniciados,Valor de conversão de checkouts iniciados,Valor de conversão de compras,Compras
0,45-54,Feminino,2021-07-31,0,1116.0,1489.0,9.42,24.00,20.00,0,0,1.00,63.90,1.00,0,0,0
1,35-44,Outros,2021-07-31,0,4.0,5.0,0.03,0,0,0,0,0,0,0,0,0,0
2,45-54,Outros,2021-07-31,0,3.0,3.0,0,0,0,0,0,0,0,0,0,0,0
3,65+,Masculino,2021-07-31,0,24.0,36.0,0.11,0,0,0,0,0,0,0,0,0,0
4,25,Outros,2021-07-31,0,4.0,4.0,0.01,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
506,55-64,Masculino,2021-07-01,0,400.0,400.0,1.07,2.00,1.00,0,0,0,0,0,0,0,0
507,65+,Feminino,2021-07-01,0,212.0,230.0,0.88,2.00,1.00,0,0,0,0,0,0,0,0
508,65+,Masculino,2021-07-01,0,136.0,157.0,0.48,0,0,0,0,0,0,0,0,0,0
509,25-34,Outros,2021-07-01,0,4.0,4.0,0,0,0,0,0,0,0,0,0,0,0
510,35-44,Outros,2021-07-01,0,NaN,5.0,0.03,0,0,0,0,0,0,0,0,0,0

#### Spliting column values to the .0 to transform then in intenger numbers, here I am creating an extra column in dataframe tha should be discarted next

In [256]:
dfIdadeGenero[['Cliques no link', 'Cliques no link2']] = dfIdadeGenero['Cliques no link'].str.split('.', expand=True)
dfIdadeGenero[['Visualizações por página', 'Visualizações por página2']] = dfIdadeGenero['Visualizações por página'].str.split('.', expand=True)
dfIdadeGenero[['Compras no website', 'Compras no website2']] = dfIdadeGenero['Compras no website'].str.split('.', expand=True)
dfIdadeGenero[['Adicionados ao carrinho', 'Adicionados ao carrinho2']] = dfIdadeGenero['Adicionados ao carrinho'].str.split('.', expand=True)
dfIdadeGenero[['Checkouts Iniciados', 'Checkouts Iniciados2']] = dfIdadeGenero['Checkouts Iniciados'].str.split('.', expand=True)
dfIdadeGenero[['Compras', 'Compras2']] = dfIdadeGenero['Compras'].str.split('.', expand=True)

In [257]:
dfIdadeGenero

,Idade,Gênero,Dia,FIELD4,Alcance,Impressões,Quantia gasta (BRL),Cliques no link,Visualizações por página,Compras no website,...,Checkouts Iniciados,Valor de conversão de checkouts iniciados,Valor de conversão de compras,Compras,Cliques no link2,Visualizações por página2,Compras no website2,Adicionados ao carrinho2,Checkouts Iniciados2,Compras2
0,45-54,Feminino,2021-07-31,0,1116.0,1489.0,9.42,24,20,0,...,1,0,0,0,00,00,None,00,00,None
1,35-44,Outros,2021-07-31,0,4.0,5.0,0.03,0,0,0,...,0,0,0,0,None,None,None,None,None,None
2,45-54,Outros,2021-07-31,0,3.0,3.0,0,0,0,0,...,0,0,0,0,None,None,None,None,None,None
3,65+,Masculino,2021-07-31,0,24.0,36.0,0.11,0,0,0,...,0,0,0,0,None,None,None,None,None,None
4,25,Outros,2021-07-31,0,4.0,4.0,0.01,0,0,0,...,0,0,0,0,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
506,55-64,Masculino,2021-07-01,0,400.0,400.0,1.07,2,1,0,...,0,0,0,0,00,00,None,None,None,None
507,65+,Feminino,2021-07-01,0,212.0,230.0,0.88,2,1,0,...,0,0,0,0,00,00,None,None,None,None
508,65+,Masculino,2021-07-01,0,136.0,157.0,0.48,0,0,0,...,0,0,0,0,None,None,None,None,None,None
509,25-34,Outros,2021-07-01,0,4.0,4.0,0,0,0,0,...,0,0,0,0,None,None,None,None,None,None
510,35-44,Outros,2021-07-01,0,NaN,5.0,0.03,0,0,0,...,0,0,0,0,None,None,None,None,None,None

#### Dropping no valuable columns from dataframe

In [258]:
dfIdadeGenero = dfIdadeGenero.drop(['Cliques no link2','Visualizações por página2','Compras no website2',
                     'Adicionados ao carrinho2','Checkouts Iniciados2','Compras2', 'FIELD4'], axis=1)

In [259]:
dfIdadeGenero

,Idade,Gênero,Dia,Alcance,Impressões,Quantia gasta (BRL),Cliques no link,Visualizações por página,Compras no website,Compras no facebook,Adicionados ao carrinho,Valor de conversão adicionado ao carrinho,Checkouts Iniciados,Valor de conversão de checkouts iniciados,Valor de conversão de compras,Compras
0,45-54,Feminino,2021-07-31,1116.0,1489.0,9.42,24,20,0,0,1,63.90,1,0,0,0
1,35-44,Outros,2021-07-31,4.0,5.0,0.03,0,0,0,0,0,0,0,0,0,0
2,45-54,Outros,2021-07-31,3.0,3.0,0,0,0,0,0,0,0,0,0,0,0
3,65+,Masculino,2021-07-31,24.0,36.0,0.11,0,0,0,0,0,0,0,0,0,0
4,25,Outros,2021-07-31,4.0,4.0,0.01,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
506,55-64,Masculino,2021-07-01,400.0,400.0,1.07,2,1,0,0,0,0,0,0,0,0
507,65+,Feminino,2021-07-01,212.0,230.0,0.88,2,1,0,0,0,0,0,0,0,0
508,65+,Masculino,2021-07-01,136.0,157.0,0.48,0,0,0,0,0,0,0,0,0,0
509,25-34,Outros,2021-07-01,4.0,4.0,0,0,0,0,0,0,0,0,0,0,0
510,35-44,Outros,2021-07-01,NaN,5.0,0.03,0,0,0,0,0,0,0,0,0,0

#### Converting columns type

In [260]:
dfIdadeGenero = dfIdadeGenero.astype({
    
    'Quantia gasta (BRL)' : float,
    'Cliques no link' : int,
    'Visualizações por página' : int,
    'Compras no website' : int, 
    'Compras no facebook' : int,
    'Adicionados ao carrinho' : int,
    'Valor de conversão adicionado ao carrinho' : float,
    'Checkouts Iniciados' : int,
    'Valor de conversão de checkouts iniciados' : int,
    'Valor de conversão de compras' : float,
    'Compras' : int    
})

In [261]:
dfIdadeGenero.dtypes

Idade                                         object
Gênero                                        object
Dia                                           object
Alcance                                      float64
Impressões                                   float64
Quantia gasta (BRL)                          float64
Cliques no link                                int32
Visualizações por página                       int32
Compras no website                             int32
Compras no facebook                            int32
Adicionados ao carrinho                        int32
Valor de conversão adicionado ao carrinho    float64
Checkouts Iniciados                            int32
Valor de conversão de checkouts iniciados      int32
Valor de conversão de compras                float64
Compras                                        int32
dtype: object

#### Replacing NaN in dataframe to 0

In [262]:
dfIdadeGenero = dfIdadeGenero.replace(np.nan, 0)

#### Renaming Columns

In [263]:
dfIdadeGenero.columns = ["idade", "genero", "dia", "alcance", 
                         "impressoes", "quantia_gasta_brl", "cliques_no_link", "visualizacoes_por_pagina",
                         "compras_no_website", "compras_no_facebook", "adicionados_ao_carrinho", 
                         "valor_de_conversao_adicionado_ao_carrinho", "checkouts_iniciados",
                         "valor_de_conversao_de_checkouts_iniciados", "valor_de_conversao_de_compras", 
                         "compras"]

#### Creating a index name column

In [264]:
index = dfIdadeGenero.index
index.name = "id"

#### Connecting to PostgreSQL database

In [265]:
conn = psycopg2.connect(host="localhost", port = 5432, database="db_alurashop", user="postgres", password="123456")

#### Creating a dataframe buffer in memory as CSV before insert data into database

In [266]:
sio = StringIO()
sio.write(dfIdadeGenero.to_csv(index=None, header=None)) 
sio.seek(0)

0

#### Inserting data into database using the temporary CSV file

In [267]:
with conn.cursor() as c:
    c.copy_from(sio, "idadegenero", columns=dfIdadeGenero.columns, sep=',')
    conn.commit()